### ISSUE TITLE
[Classic] Debian BUILD Error 

### ISSUE THREAD

**Issue by wowmui** [51kfa/mangos-classic#1]
大神您好,自己在debian上下载您的端自己编译了试下,发现没法通过...难道是少装了什么库还是要改cpp文件??

> Linking CXX static library libgame.a
> [ 55%] Built target game
> Linking CXX executable mangosd
> ../game/libgame.a(Player.cpp.o): In function `Player::Player(WorldSession*)':
> Player.cpp:(.text+0x20c9d): undefined reference to`AntiCheat::AntiCheat(Player_)'
> ../game/libgame.a(Player.cpp.o): In function `Player::~Player()':
> Player.cpp:(.text+0x407d7): undefined reference to`AntiCheat::~AntiCheat()'
> ../game/libgame.a(Player.cpp.o): In function `Player::_SaveInventory()':
> Player.cpp:(.text+0x41183): undefined reference to`AntiCheat::_DoAntiCheatCheck(AntiCheat
> Check)'collect2: error: ld returned 1 exit status
> src/mangosd/CMakeFiles/mangosd.dir/build.make:271: recipe for target 'src/mangosd/mangosd'
>  failedmake[2]: *_\* [src/mangosd/mangosd] Error 1
> CMakeFiles/Makefile2:755: recipe for target 'src/mangosd/CMakeFiles/mangosd.dir/all' faile
> dmake[1]: **\* [src/mangosd/CMakeFiles/mangosd.dir/all] Error 2
> Makefile:117: recipe for target 'all' failed
> make: **\* [all] Error 2
> cmangos@iZ234pvm4y9Z:~/mangos-classic/build$ 

编译到这就错了....Debian,我编译mangoszero和Cmangos都挺好..这个怎么回事..

**Comment by wowmui** [comment]
cmake执行

> cmake  ../mangos-classic/ -DCMAKE_INSTALL_PERFIX=/home/cmangos/51run

然后有几个warrning

> -- This script builds the MaNGOS server.
>   Options that can be used in order to configure the process:
>     CMAKE_INSTALL_PREFIX    Path where the server should be installed to
>     PCH                     Use precompiled headers
>     DEBUG                   Include additional debug-code in core
>     WARNINGS                Show all warnings during compile
>     INCLUDE_BINDINGS_DIR    Include a script library in src/bindings/ with the
>                             defined name. the name must corespond to the name of
>                             the folder and the folder must contain a valid
>                             CMakeLists.txt
>     TBB_USE_EXTERNAL        Use external TBB
>     USE_STD_MALLOC          Use standard malloc instead of TBB
>     ACE_USE_EXTERNAL        Use external ACE
>   To set an option simply type -D<OPTION>=<VALUE> after 'cmake <srcs>'.
>   Also, you can specify the generator with -G. see 'cmake --help' for more details
>   For example: cmake .. -DDEBUG=1 -DCMAKE_INSTALL_PREFIX=/opt/mangos
> 
> -- Detected 64-bit platform
> -- UNIX: Configuring uninstall target
> -- UNIX: Created uninstall target
> -- UNIX: Detected compiler: /usr/bin/cc
> -- GCC: SFMT enabled, SSE2 flags forced
> -- Using mysql-config: /usr/bin/mysql_config
> -- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient_r.so
> -- Found MySQL headers: /usr/include/mysql
> -- CMaNGOS-Core revision : 55431334ee92e1f5f24483680e78eb9165bebb1d
> -- Install server to     : /usr/local
> -- Build script library  : No
> -- Use PCH               : No
> -- Build in debug-mode   : No  (default)
> 
> -- Configuring done
> CMake Warning (dev) in CMakeLists.txt:
>   Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
>   Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in CMakeLists.txt:
>   Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
>   Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in CMakeLists.txt:
>   Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
>   Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/framework/CMakeLists.txt:
>   Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
>   Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/shared/CMakeLists.txt:
>   Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
>   Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/realmd/CMakeLists.txt:
>   Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
>   Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/game/CMakeLists.txt:
>   Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
>   Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/mangosd/CMakeLists.txt:
>   Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
>   Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/scriptdev2/CMakeLists.txt:
>   Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
>   Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by 51kfa** [comment]
对不起，加了反外挂的代码后忘记更新CMakeLists.txt了，现在才被发现，谢谢你的关注

**Comment by wowmui** [comment]
谢谢,还有为发现一个很影响游戏内交流的bug, 频道有问题,切换地图,综合频道就被吃了,世界频道也自动退了, 除了本地防务是好的,其他几个频道都不能用了.
